### ISSUE TITLE
Works in tests, not during real launches

### ISSUE THREAD

**Issue by psychonaut25** [KSP-RO/RealPlume#36]
I built a test using one of my SpaceY SRBs facing downwards on the launchpad, and RealPlume works beautifully.  But when I build an actual rocket and try to launch it, RealPlume produces a tiny, tiny plume that looks significantly worse than the stock game.

Test: https://ibb.co/fM60HR
Actual Launch: https://ibb.co/mQNUBm

**Comment by Nhawks1717** [comment]
Hmm.... which SRB is this? The plume looks way too small.... I don't remember seeing this in my testing but I may have mucked something up.

**Comment by psychonaut25** [comment]
It's the SpaceY 05S SRB

**Comment by Nhawks1717** [comment]
Ahh... Did you perhaps scale the SRB up? That's why the plume is very small.

In regards to the actual launch it's because of the particle count limit that SmokeScreen is set to. You can try a higher value by either changing it in the SmokeScreen settings.cfg file and reloading the game or by using the toolbar mod and using the SmokeScreen button to open the settings in-game and changing the value.

**Comment by psychonaut25** [comment]
Well, yes, I did scale it up, but I did that for the test with the booster upside down as well.  The thing that really confuses me is that it behaves differently in each case despite being scaled to the same size in both cases.

I'll give your suggestion a shot, though.

**Comment by psychonaut25** [comment]
Hey there, apologies for taking so long to get back to you, but that did pretty much solve my problem, so thank you.  I'm closing the issue now.

**Comment by psychonaut25** [comment]
The problem seems to have arisen again, and changing the value in the SmokeScreen cfg file had no effect this time :/

Is there a way to simply disable Realplume for a specific part?  I'm getting kind of tired of this.  Perhaps I could just delete cfg files for SRBs?
