### ISSUE TITLE
[Enhancement] Add Faint Black smoke to Kerolox Plumes

### ISSUE THREAD

**Issue by Chandra-Aerospace** [KSP-RO/RealPlume#75]
I would Like to see some Faint Kerolox Exhaust smoke.

If you have seen a Saturn V launch On youtube, You have seen some dark, faint smoke after the plume.

**Comment by zorg2044** [comment]
trailing smoke is the bane of my existence :P 

So a smoke effect like the SRB smoke, that has world velocity (so that it persists) is kind of difficult to work with and has high performance impact (however for a kerolox plume it doesnt need to as dense I guess).

I am looking at some enhancements for kerolox plumes for the next version of BDB and will likely port any improvements over. I will consider making one kerolox plume with a faint trailing exhaust IF I can come up with a nice effect and configure it to look attractive.

My last attempt went horribly wrong but that was some time ago. Let's see how it goes next time but might be a little while before I can get to this.

**Comment by Chandra-Aerospace** [comment]
Sounds good!
